CREATE TABLE LOGIN (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  
  MUTEMUSIC BOOLEAN NOT NULL,
  LOOPMUSIC BOOLEAN NOT NULL,
  MUTESFX BOOLEAN NOT NULL,
  MUSICVALUE DOUBLE PRECISION NOT NULL,
  SFXVOLUME DOUBLE PRECISION NOT NULL,
  RESOLUTIONWIDTH INTEGER NOT NULL,
  RESOLUTIONHEIGHT INTEGER NOT NULL,
  DEBUG BOOLEAN NOT NULL,
  
  PRIMARY KEY (USERNAME)
);